### ISSUE TITLE
Warning: Could not find a declaration file for module 'three-full'. 

### ISSUE THREAD

**Issue by rudza** [Itee/three-full#12]
```[ts]
Could not find a declaration file for module 'three-full'. '/home/rudolfs/workspace/VZChains/blocstate/node_modules/three-full/builds/Three.cjs.js' implicitly has an 'any' type.
Try `npm install @types/three-full` if it exists or add a new declaration (.d.ts) file containing `declare module 'three-full';`
module "/node_modules/three-full/builds/Three.cjs"```

**Comment by Itee** [comment]
Thanks for feedback, this is related to #10 

The latest release v11.3.2 should fix it

**Comment by CreativeHouseDotOrg** [comment]
Thank you for your reply. I've tried your approach and it didn't solve the issue. See the screenshot below:

![ErrorOutput](https://user-images.githubusercontent.com/4038603/52003061-d3137080-24c3-11e9-8b2b-f338b07f651f.PNG)

I am referring from this Topic:
[How do I include THREE.LensFlareElement in Angular Project?](https://discourse.threejs.org/t/how-do-i-include-three-lensflareelement-in-angular-project/5885/9)

As from @Mugen87's reply:

>  Fortunately, there will be a node script with the next release R101 that can generate modules from example files: [Added script to generate modules out of example/js files](https://github.com/mrdoob/three.js/pull/15518)

Whereas on the [Milestone Page](https://github.com/mrdoob/three.js/milestones) the progressbar indicates 42% complete. So i don't think that there will be an easy solution in near time for using example based classes, even with third-party libraries or templates.

Anyway I'll just leave this as a review for the angular template (non-ionic version) and thank you for your time.

Creative Regards

**Comment by Itee** [comment]
Could i close this issue or have you still trouble ?
